blank_issues_enabled: false

contact_links:
  - name: Authors
    url: https://github.com/robotstech/opensource-project/blob/main/README.md#Authors/Contributors
    about: checkout the README for list of contributors
